ARG BASE_OS
FROM "$BASE_OS"

RUN DEBIAN_FRONTEND="noninteractive" apt-get update

# Build tools
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y make cmake build-essential python3-venv

# Required for LV_USE_SDL
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y libsdl2-dev libsdl2-image-dev

# Required for LV_USE_LINUX_DRM linux-headers-generic provides an included header file
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y libevdev-dev libdrm-dev linux-headers-generic

# Required for libcurl (for fetch_schedule_data in api.c)
RUN DEBIAN_FRONTEND="noninteractive" apt-get install -y libcurl4-openssl-dev

RUN mkdir /workdir
WORKDIR /workdir
